import { Zap } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <a href="/" className="inline-flex items-center gap-2 mb-10">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-accent flex items-center justify-center shadow-sm">
            <Zap className="w-4 h-4 text-white" />
          </div>
          <span className="text-lg font-bold text-foreground">Repurpose<span className="gradient-text">Hub</span></span>
        </a>

        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted mb-10">Last updated: April 2, 2026</p>

        <div className="prose-sm space-y-8 text-foreground/80 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using RepurposeHub, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>RepurposeHub is an AI-powered content repurposing platform that transforms your text into adapted versions for multiple social media platforms. The service includes a web application and a Chrome browser extension.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. Accounts</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must provide a valid email address to create an account</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must be at least 13 years old to use the service</li>
              <li>One person or entity per account; accounts cannot be shared</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. Your Content</h2>
            <p>You retain full ownership of the content you submit and the content generated for you. By using RepurposeHub, you grant us a limited license to process your content solely for the purpose of providing the service.</p>
            <p className="mt-2">You are responsible for ensuring you have the right to use and repurpose any content you submit. Do not submit content that infringes on others&apos; intellectual property rights.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Acceptable Use</h2>
            <p>You agree not to use RepurposeHub to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Generate spam, misleading, or harmful content</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Attempt to reverse-engineer, hack, or disrupt the service</li>
              <li>Resell or redistribute the service without authorization</li>
              <li>Circumvent usage limits or abuse the platform</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. Plans and Billing</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Free plan:</strong> 30 generations per month, limited features</li>
              <li><strong>Pro plan:</strong> $29/month, unlimited generations, advanced features</li>
              <li><strong>Agency plan:</strong> $79/month, team features, API access</li>
              <li>Paid subscriptions are billed monthly via Stripe</li>
              <li>You may cancel your subscription at any time; access continues until the end of the billing period</li>
              <li>Refunds are handled on a case-by-case basis</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. AI-Generated Content</h2>
            <p>Content generated by RepurposeHub is produced using AI and may not always be accurate, appropriate, or suitable for your needs. You are responsible for reviewing and editing all generated content before publishing. RepurposeHub is not liable for any consequences of publishing AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. Service Availability</h2>
            <p>We strive to maintain high availability but do not guarantee uninterrupted service. We may modify, suspend, or discontinue features with reasonable notice. Scheduled maintenance will be communicated in advance when possible.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9. Limitation of Liability</h2>
            <p>RepurposeHub is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">10. Termination</h2>
            <p>We may terminate or suspend your account if you violate these terms. You may delete your account at any time from your settings page. Upon termination, your data will be deleted within 30 days.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">11. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms. We will notify users of significant changes via email.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">12. Contact</h2>
            <p>For questions about these terms, contact us at info@repurposehub.co.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
